# Generated by Django 3.2.7 on 2021-09-13 01:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountapp', '0002_auto_20210912_1300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_superuser',
        ),
    ]
